source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'bookMatch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bookMatch
    pod 'FirebaseUI/Auth'
    pod 'Firebase/Analytics'

  target 'bookMatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bookMatchUITests' do
    # Pods for testing
  end

end
